[tool.poetry]
name = "translate"
version = "0.1.0"
description = ""
authors = ["gbPagano <guilhermebpagano@gmail.com>"]
readme = "README.md"
packages = [{ include = "terminal-translator", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
google-cloud-translate = "^3.11.0"
dynaconf = "^3.1.12"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
